;;; vercel-theme.el --- Ghostty Vercel-inspired dark theme -*- lexical-binding: t -*-

(deftheme vercel
  "A dark theme based on Ghostty's bundled Vercel palette.")

(let (;; Palette mirrors Ghostty's bundled Vercel theme.
      (bg "#101010")
      (bg-alt "#161616")
      (bg-soft "#1d1d1d")
      (bg-softer "#262626")
      (fg "#fafafa")
      (fg-muted "#a8a8a8")
      (fg-subtle "#737373")
      (border "#333333")
      (selection "#005be7")
      (accent "#006aff")
      (accent-strong "#49aeff")
      (green "#29a948")
      (yellow "#ffae00")
      (orange "#ffae00")
      (red "#fc0036")
      (red-bright "#ff8080")
      (purple "#f32882")
      (purple-bright "#f97ea8")
      (cyan "#00ac96")
      (cyan-bright "#00e4c4"))
  (custom-theme-set-faces
   'vercel
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,purple))))
   `(fringe ((t (:background ,bg :foreground ,fg-subtle))))
   `(region ((t (:background ,selection :foreground ,fg))))
   `(highlight ((t (:background ,bg-softer))))
   `(hl-line ((t (:background ,bg-alt))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(window-divider-first-pixel ((t (:foreground ,border))))
   `(window-divider-last-pixel ((t (:foreground ,border))))
   `(minibuffer-prompt ((t (:foreground ,accent-strong :weight bold))))
   `(escape-glyph ((t (:foreground ,yellow))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))

   `(mode-line ((t (:background ,fg :foreground ,bg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-soft :foreground ,fg-subtle :box (:line-width 1 :color ,border)))))
   `(mode-line-buffer-id ((t (:weight bold))))
   `(header-line ((t (:background ,bg-soft :foreground ,fg-muted :box nil))))

   `(line-number ((t (:background ,bg :foreground ,fg-subtle))))
   `(line-number-current-line ((t (:background ,bg-alt :foreground ,fg))))
   `(show-paren-match ((t (:background ,accent :foreground "#ffffff" :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground "#ffffff" :weight bold))))
   `(trailing-whitespace ((t (:background ,red))))

   `(link ((t (:foreground ,accent-strong :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(button ((t (:foreground ,accent-strong :underline t))))

   `(font-lock-builtin-face ((t (:foreground ,purple))))
   `(font-lock-comment-face ((t (:foreground ,fg-subtle :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,fg-subtle :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,cyan))))
   `(font-lock-doc-face ((t (:foreground ,fg-muted :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,accent-strong))))
   `(font-lock-keyword-face ((t (:foreground ,purple :weight medium))))
   `(font-lock-negation-char-face ((t (:foreground ,red))))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,yellow :weight bold))))

   `(isearch ((t (:background ,yellow :foreground ,bg :weight bold))))
   `(isearch-fail ((t (:background ,red :foreground "#ffffff" :weight bold))))
   `(lazy-highlight ((t (:background ,bg-softer :foreground ,yellow))))
   `(match ((t (:background ,bg-softer :foreground ,accent-strong :weight bold))))

   `(completions-common-part ((t (:foreground ,accent-strong))))
   `(completions-first-difference ((t (:foreground ,yellow :weight bold))))
   `(shadow ((t (:foreground ,fg-subtle))))
   `(secondary-selection ((t (:background ,bg-softer))))
   `(tooltip ((t (:background ,bg-soft :foreground ,fg :box (:line-width 1 :color ,border)))))

   `(dired-directory ((t (:foreground ,accent-strong :weight bold))))
   `(dired-flagged ((t (:foreground ,red))))
   `(dired-header ((t (:foreground ,fg :weight bold))))
   `(dired-ignored ((t (:foreground ,fg-subtle))))
   `(dired-mark ((t (:foreground ,yellow :weight bold))))
   `(dired-marked ((t (:foreground ,purple :weight bold))))
   `(dired-perm-write ((t (:foreground ,fg-muted))))
   `(dired-symlink ((t (:foreground ,cyan))))
   `(dired-warning ((t (:foreground ,yellow))))

   `(diff-added ((t (:background "#092f1f" :foreground ,green))))
   `(diff-changed ((t (:background "#332600" :foreground "#ffd166"))))
   `(diff-removed ((t (:background "#3a1015" :foreground ,red-bright))))
   `(diff-refine-added ((t (:background "#0f5132" :foreground "#4be15d"))))
   `(diff-refine-changed ((t (:background "#5c3d00" :foreground "#ffe28a"))))
   `(diff-refine-removed ((t (:background "#67060c" :foreground "#ffd7d5"))))
   `(diff-header ((t (:background ,bg-soft :foreground ,fg-muted))))
   `(diff-file-header ((t (:background ,bg-soft :foreground ,fg :weight bold))))

   `(magit-section-heading ((t (:foreground ,fg :weight bold))))
   `(magit-branch-current ((t (:foreground ,accent-strong :weight bold))))
   `(magit-branch-local ((t (:foreground ,accent-strong))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(magit-diff-added ((t (:background "#092f1f" :foreground ,green))))
   `(magit-diff-added-highlight ((t (:background "#0f5132" :foreground "#4be15d"))))
   `(magit-diff-removed ((t (:background "#3a1015" :foreground ,red-bright))))
   `(magit-diff-removed-highlight ((t (:background "#67060c" :foreground "#ffd7d5"))))
   `(magit-diff-context ((t (:background ,bg :foreground ,fg-muted))))
   `(magit-diff-context-highlight ((t (:background ,bg-alt :foreground ,fg))))
   `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-soft :foreground ,fg :weight bold))))
   `(magit-hash ((t (:foreground ,fg-subtle))))

   `(org-block ((t (:background ,bg-soft :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,bg-soft :foreground ,fg-subtle))))
   `(org-block-end-line ((t (:background ,bg-soft :foreground ,fg-subtle))))
   `(org-code ((t (:foreground ,cyan))))
   `(org-date ((t (:foreground ,accent-strong))))
   `(org-document-title ((t (:foreground ,fg :weight bold :height 1.25))))
   `(org-level-1 ((t (:foreground ,fg :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,accent-strong :weight bold))))
   `(org-level-3 ((t (:foreground ,purple-bright :weight bold))))
   `(org-level-4 ((t (:foreground ,cyan-bright :weight bold))))
   `(org-link ((t (:foreground ,accent-strong :underline t))))
   `(org-meta-line ((t (:foreground ,fg-subtle))))
   `(org-quote ((t (:background ,bg-soft :foreground ,fg-muted :slant italic))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))

   `(markdown-header-face ((t (:foreground ,fg :weight bold))))
   `(markdown-header-face-1 ((t (:foreground ,fg :weight bold :height 1.15))))
   `(markdown-header-face-2 ((t (:foreground ,accent-strong :weight bold))))
   `(markdown-header-face-3 ((t (:foreground ,purple-bright :weight bold))))
   `(markdown-code-face ((t (:background ,bg-soft :foreground ,cyan))))
   `(markdown-pre-face ((t (:background ,bg-soft :foreground ,fg))))
   `(markdown-link-face ((t (:foreground ,accent-strong :underline t))))

   `(vertico-current ((t (:background ,bg-softer :foreground ,fg))))
   `(orderless-match-face-0 ((t (:foreground ,accent-strong :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,purple-bright :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,cyan-bright :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,yellow :weight bold))))
   `(marginalia-documentation ((t (:foreground ,fg-subtle))))
   `(marginalia-file-name ((t (:foreground ,fg))))
   `(marginalia-date ((t (:foreground ,fg-subtle))))
   `(consult-highlight-match ((t (:foreground ,accent-strong :weight bold))))

   `(corfu-default ((t (:background ,bg-soft :foreground ,fg))))
   `(corfu-current ((t (:background ,bg-softer :foreground ,fg))))
   `(corfu-border ((t (:background ,border))))
   `(corfu-annotations ((t (:foreground ,fg-subtle))))
   `(popup-face ((t (:background ,bg-soft :foreground ,fg))))
   `(posframe ((t (:background ,bg-soft :foreground ,fg))))
   `(posframe-border ((t (:background ,border))))

   `(which-key-key-face ((t (:foreground ,accent-strong :weight bold))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-group-description-face ((t (:foreground ,purple-bright))))
   `(which-key-local-map-description-face ((t (:foreground ,cyan-bright))))
   `(transient-heading ((t (:foreground ,fg :weight bold))))
   `(transient-key ((t (:foreground ,accent-strong :weight bold))))
   `(transient-argument ((t (:foreground ,yellow))))
   `(transient-value ((t (:foreground ,green))))

   `(lsp-face-highlight-textual ((t (:background ,bg-softer))))
   `(lsp-face-highlight-read ((t (:background ,bg-softer))))
   `(lsp-face-highlight-write ((t (:background ,selection))))
   `(lsp-ui-doc-background ((t (:background ,bg-soft))))
   `(lsp-ui-doc-header ((t (:background ,bg-softer :foreground ,fg :weight bold))))
   `(lsp-ui-sideline-code-action ((t (:foreground ,yellow))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,fg))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,accent-strong))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,purple))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,cyan))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,green))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,yellow))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,orange))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,red))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,fg-muted))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold)))))

  (custom-theme-set-variables
   'vercel
   '(ansi-color-names-vector
     ["#000000" "#fc0036" "#29a948" "#ffae00" "#006aff" "#f32882" "#00ac96" "#feffff"])
   `(frame-background-mode 'dark)))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(provide-theme 'vercel)

;;; vercel-theme.el ends here
